/* eslint-disable */
// This file is auto-generated by Convex
// Run `npx convex dev` to regenerate

import type {
  GenericMutationCtx,
  GenericQueryCtx,
  FunctionReference,
} from 'convex/server';

type QueryCtx = GenericQueryCtx<any>;
type MutationCtx = GenericMutationCtx<any>;

export declare function query<Args extends Record<string, any>, Output>(func: {
  args: Args;
  handler: (ctx: QueryCtx, args: any) => Output | Promise<Output>;
}): FunctionReference<'query'>;

export declare function mutation<Args extends Record<string, any>, Output>(func: {
  args: Args;
  handler: (ctx: MutationCtx, args: any) => Output | Promise<Output>;
}): FunctionReference<'mutation'>;

export declare function internalQuery<Args extends Record<string, any>, Output>(func: {
  args: Args;
  handler: (ctx: QueryCtx, args: any) => Output | Promise<Output>;
}): FunctionReference<'query'>;

export declare function internalMutation<Args extends Record<string, any>, Output>(func: {
  args: Args;
  handler: (ctx: MutationCtx, args: any) => Output | Promise<Output>;
}): FunctionReference<'mutation'>;
